apiVersion: v1
kind: Service
metadata:
  name: flight-price-service
spec:
  selector:
    app: flight-price-api
  type: NodePort            # or LoadBalancer on cloud
  ports:
    - port: 5000            # cluster‑internal port
      targetPort: 5000      # container port
      nodePort: 30080       # external port (only for NodePort)
